#!/bin/bash
set -x
CE_SOURCES=($(ls ce/*.c | grep -v test))
FLAGS='-shared -Wall -Werror -Wshadow -Wextra -Wno-unused-parameter -std=gnu11 -ggdb3 -fpic -rdynamic -DDISPLAY_GUI -I/usr/include/SDL2'
#FLAGS='-shared -Wall -Werror -Wshadow -Wextra -Wno-unused-parameter -std=gnu11 -ggdb3 -DDISPLAY_GUI -I/usr/include/SDL2' # for cygwin, annoyingly
SHARED_OBJ='ce_config_gui.so'
LINK='-lSDL2 -lSDL2_ttf'
clang $FLAGS ${CE_SOURCES[*]} ce_config.c $LINK -o $SHARED_OBJ

